### ISSUE TITLE
提取码功能

### ISSUE THREAD

**Issue by s1ntoneli** [delbertbeta/rajio#1]
嗨 小伙子。
我之前也有一样的想法，不过自己做安卓而不是前端，所以草草弄了一下，这是我的地址 [tiny.antiless.com](tiny.antiless.com)

两个建议给你，希望你能越做越好：

### 其一，提供一个**4~6位的提取码**，用于唯一对应一个文件，可通过它下载文件。

二维码是个不错的想法，给你点赞。

不过，我在使用过程中发现另一个分享方式依赖度会非常高，而且它可以抛弃二维码的一个缺点——接收方必须有摄像头。

而提取码，和验证码一样，能瞬间记住并在其它地方输入，也不会一直占据大脑空间。用来下载文件再合适不过了。因为可用的场景，相对于二维码扩展了很多。

### 其二，换个短一点的域名

你的域名太长了。。我很多时候使用中转站都是为了快速在多端间转移文件。

而你的域名是 rajio.delbertbeta.cc .....

虽然浏览器有历史补全功能，但是我很可能第一时间想不起来有个文件中转站的域名是 rajio 开头的啊/(ㄒoㄒ)/~~

加油吧，如果你能加了提取码这个功能，我可能会试着抛弃我那个破破烂烂的页面，转来使用你这个了。毕竟颜就是正义!

**Comment by delbertbeta** [comment]
@auv1107 

你好，很高兴你能给我提出建议。

* 其一，提供一个4~6位的提取码，用于唯一对应一个文件，可通过它下载文件。

提取码一直都是存在的，其实就是产生的URL的后面的6位字母和数字

例如：
```
https://rajio.delbertbeta.cc/s/2ad88d
```
中的`2ad99d`

可能是我没有把它放到醒目的地方，再加上也没有相应的入口，导致了并不是特别直观。因为在自用的时候我明白这个功能点的设计，就会自己去输入rajio.delbertbeta.cc/s/再加上那个提取码直达下载页面。这个功能会马上加上的。

* 其二，换个短一点的域名

不是我不想换，而是没钱啊T_T，国内买域名便宜但是都要备案了，国外域名老贵老贵的，目前想法是接入第三方短地址服务吧，你觉得呢？

**Comment by s1ntoneli** [comment]
看到你把提取码加上了，我的站可以宣布退休了哈哈。
短链的事，在我看来短链本身有一串不可拼写的字符串，不是很合适，相对来说还是当前的域名更好点。

还有件事，我想暂时把我主站上文件中转的入口换成rajio，你看可以吗？
![image](https://user-images.githubusercontent.com/2681464/48926440-158b6080-ef09-11e8-87f0-17e22336ffbb.png)

**Comment by delbertbeta** [comment]
@auv1107 可以呀，非常感谢～我也稍微看了一下目前的短链接服务，生成的URL反而更加难用了。所以这个计划先搁置吧，还是等有钱搞个域名好了 :rofl:
