### ISSUE TITLE
能分享文字吗？

### ISSUE THREAD

**Issue by potoo0** [delbertbeta/rajio#3]
你的这个可以分享文字吗？

对了，这里有个非常强大的分享网站，但是国内访问速度太差了，经常进不去。很想布置在我的树莓派上，但可惜不开源T_T

**Comment by delbertbeta** [comment]
一直计划做了，但是最近是面试季，我也要先找口饭吃😂咕咕咕。有 offer 了文本分享马上上线hhhhhh

**Comment by potoo0** [comment]
好的。期待中。我也是在筹备工作中，祝我们都好运～
